### ISSUE TITLE
Typo in serviceaccount.yaml

### ISSUE THREAD

**Issue by fabhuebner** [FusionAuth/charts#112]
**Describe the bug**
yaml structure is not parsed correctly
error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string

**Docker version and underlying OS**
n/a

**To Reproduce**
```
### values.yaml ###
serviceAccount:
  create: true
  name: fusionauth
  annotations:
    iam.gke.io/gcp-service-account: fusionauth@[xxx].iam.gserviceaccount.com
```

**Expected behavior**
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: fusionauth@[xxx].iam.gserviceaccount.com
  name: fusionauth
```

**Logs (please share snips of applicable logs)**
`error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string`

**Additional context**
https://github.com/FusionAuth/charts/blob/main/chart/templates/serviceaccount.yaml#L6
replace `if` with `with`
```
 {{- with .Values.serviceAccount.annotations }}
```
