### ISSUE TITLE
Support valueFrom/secretKeyRef

### ISSUE THREAD

**Issue by ceefour** [FusionAuth/charts#17]
Especially for:

* `database.password`
* `database.root.password`

Currently these values has to be specified to helm chart literally.

It'd be great if we can say:

```yaml
secretName: fusionauth

database:
  passwordSecretKey: mariadb-password
  root:
    passwordSecretKey: mariadb-root-password
```

And the generated template will use `valueFrom`/`secretKeyRef`.
