### ISSUE TITLE
Setting replicas greater than 1, could not login

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#19]
Can you confirm increasing the number of replicas _(pods)_ should work? When I had it set to 3 replicas could not login. Immediately after the wizard, I was kicked into an infinite loop at the oauth screen. I know I was using the correct credentials because when I didn't, I saw a validation error. I recreated the deployment setting replicas to 1 and it worked. Want to confirm.

Is there per-process, in-memory caching perhaps that would be breaking support for multiple replicas?

Using our own out of chart PostgreSQL and Elasticsearch.

**Comment by drpebcak** [comment]
I believe running more than 1 fusionauth server requires sticky sessions. You would need some additional configuration for your ingress/service to make that happen.

**Comment by nodesocket** [comment]
@drpebcak does this helm chart support adding annotations to the service? I need to add:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
```
