### ISSUE TITLE
Allow specification of dnsConfig in the deployment

### ISSUE THREAD

**Issue by fdlk** [FusionAuth/charts#29]
As a workaround for https://github.com/FusionAuth/fusionauth-containers/issues/54 we would like to specify dnsConfig in the deployment, but the chart does not allow it.
(I can imagine that there may be other reasons why you'd want to specify it on specific clusters)

```
dnsConfig:
  options:
    - name: ndots
      value: "1"
```
