### ISSUE TITLE
Search port required even when search is set to database

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#46]
When using `search: engine: database` the chart enforces that `port` be an integer. It should not validate this field since the comment above says:

> search.port -- Port to use when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch

```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
fusionauth:
- search.port: Invalid type. Expected: integer, given: string
```

Relevant block in my `values.yaml`

```
  search:
    # search.engine -- Defines backend for fusionauth search capabilities. Valid values for engine are 'elasticsearch' or 'database'.
    engine: database
    # search.engine -- Protocol to use when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch
    protocol: ""
    # search.host -- Hostname or ip to use when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch
    host: ""
    # search.port -- Port to use when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch
    port:
    # search.user -- Username to use with basic auth when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch
    # user: ""
    # search.password -- Password to use with basic auth when connecting to elasticsearch. Ignored when search.engine is NOT elasticsearch
    # password: ""
```
