### ISSUE TITLE
busybox:latest -- toomanyrequests work around

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#47]
As I understand, if I provide authentication to Docker Hub I can get around the rate limits on pulling `busybox`. I tried adding `imagePullSecrets` to the `initImage ` block, but I am still  getting:

```
Failed to pull image `busybox:latest": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Example:

```
# This image should contain `nc` and a shell of some kind to do a simple loop.
initImage:
  # initImage.repository -- Docker image to use for initContainers
  repository: busybox
  # initImage.repository -- Tag to use for initContainers docker image
  tag: latest
  imagePullSecrets:
    - regcred
```

`regcred` is a secret that contains valid Docker Hub credentials.
