### ISSUE TITLE
upgrade from 0.8.1 to 0.9.2 failed

### ISSUE THREAD

**Issue by sw34** [FusionAuth/charts#51]
I have the database passwords set in an existing secret ```existingSecret: fusionauth-db```, when updating from chart 0.8.1 to 0.9.2 the silent database update process failed on the pod, complaining that pgsql required a password but none was supplied.

changing back to 0.8.1 resolved the issue.

I tried removing the password line that is set to empty string, but the validation failed.

```
database:
  existingSecret: fusionauth-db
  host: XXXXXXXXXXXXXXXXX
  name: fusionauth
  password: ''
```

**Comment by drpebcak** [comment]
Are you providing a root user/password? It sounds like this failure is inside the application itself, not the chart. I don't personally use the silent upgrade process, but if it just uses the same credentials as the rest of fusionauth, I don't see anything obvious jumping out at me from the info you have provided.

**Comment by drpebcak** [comment]
I will say, you don't need to provide anything for the password here, but you should provide the username.

**Comment by sw34** [comment]
I should have mentioned I was also updating the image from 1.26.1 to 1.27.2 at the same time.

I just updated the chart to 0.9.2 and all seems well so it must have been part of the image update as well.

over the weekend I will try the same process on my production server.

When I first made the update to 0.9.2 I took the exact same set of chart values that had been running in 0.8.1, with the exception of the image.tag moving from 1.26.1 to 1.27.2.  It was the database update that failed, saying it couldn't log in due to blank password, I switched back to chart version 0.8.1 (with the image.tag set to 1.27.2 in my values.yaml) and it updated as expected.

**Comment by sw34** [comment]
Here is the meat of my values.yaml

```
affinity: {}
annotations: {}
app:
  memory: 256M
  runtimeMode: production
database:
  existingSecret: fusionauth-db
  host: XXXXXXXXXXXXXXXXXXXXXX
  name: fusionauth
  password: ''
  port: 5432
  protocol: postgresql
  root:
    password: ''
    user: postgres
  tls: false
  tlsMode: require
  user: fusionauth
dnsConfig: {}
dnsPolicy: ClusterFirst
environment:
  - name: FUSIONAUTH_APP_SILENT_MODE
    value: 'true'
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: fusionauth/fusionauth-app
  tag: 1.27.2
```

**Comment by drpebcak** [comment]
Just so you know, if you aren't changing the default, you don't need to include keys in your override values.yaml.

```
affinity
annotations
app.runtimeMode
database.name
database.password
database.port
database.protocol
database.root.password
database.tls
database.tlsMode
dnsConfig
dnsPolicy
fullnameOverride
iamge.pullPolicy
image.repository
```
Are all set to their defaults in your config.

**Comment by drpebcak** [comment]
If you could share the redacted yaml of your existing secret that would be helpful as well. I essentially just want to know what keys exist, obviously i dont need the actual passwords.

**Comment by sw34** [comment]
```
apiVersion: v1
data:
  password: XXXXXXXXXXXXXXXXXXXXXXX
  rootpassword: XXXXXXXXXXXXXXXXXXXXXXX
kind: Secret
metadata:
  name: fusionauth-db
  namespace: fusionauth
type: Opaque
```
