### ISSUE TITLE
Hosts must be explicitly set to the full service names

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#7]
The only way I was able to get this chart working, was by using the inherited PostgreSQL and Elasticsearch. However, even that required me to set the hosts explicitly:

```
database:
    host: "fusionauth-postgresql.default.svc.cluster.local"
    port: 5432
    tls: false
    name: fusionauth
    user: localhost
    password: localhost
    root:
      user: localhost
      password: localhost

  search:
    protocol: http
    host: "fusionauth-elasticsearch-client.default.svc.cluster.local"
    port: 9200
    # user: ""
    # password: ""
```

Leaving the hosts as `""` would fail the pod init connecting to Elasticsearch.

Trying to use our own Elasticsearch and PostgreSQL caused a slew of others problems.
