### ISSUE TITLE
Helm not able to evaluate hosts value when upgrading to the latest version

### ISSUE THREAD

**Issue by soroushtaheri** [FusionAuth/charts#72]
**Describe the bug**
Trying to upgrade from v0.9.3 to 0.10.3. After executing `helm upgrade ...` command, I get an error from helm which most likely is related to parsing the `values.yaml` file.
```
Error: UPGRADE FAILED: template: fusionauth/templates/ingress.yaml:31:18: executing "fusionauth/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
```
`values.yaml` file (Ingress part):
```
ingress:
   annotations:
     ...
   enabled: true
   hosts:
     - fusion.example.com
   paths:
     - "/"
  tls:
    - hosts:
        - fusion.example.com
      secretName: fusionauth-tls

```
According to the documentations, everything about the `values.yaml` file seems about right. Although, going through the list of commits for the `ingress.yaml` file, it seems like 5fb917a has recently changed the structure of that file a bit. I believe that commit might have caused this issue.

**To Reproduce**
Write the `ingress` part of your `values.yaml` with a similar structure to what's mentioned above and then try to upgrade your release to the latest version.

**Expected behavior**
Properly upgrade the fusionauth release to the latest version (0.10.3) without any problems.

**Comment by drpebcak** [comment]
Your values.yaml does not match the format given in the default values.yaml -

```
tls:
  - secretName: fusionauth-tls
    hosts:
      - fusion.example.com
```

**Comment by soroushtaheri** [comment]
Sorry. I made a mistake while copying the values. The tls part is exactly the same as what you wrote. (I updated the post)
But again, if you pay enough attention to the error, you can see that it's actually related to `ingress.hosts` and **not** `ingress.tls`. ([`fusionauth/templates/ingress.yaml:31`](https://github.com/FusionAuth/charts/blob/76ad034e9502c3599928afbffe96255965e13139/chart/templates/ingress.yaml#L31) refers to `ingress.hosts`)

Therefore, I should still get the error - which I do and is totally expected.

**Comment by dev-ago** [comment]
Hi,

i have the same issue and i get the error in the chart with the app version: `1.30.1` and commit `76ad034`

### Error Message:
```
Error: template: fusionauth/templates/ingress.yaml:31:18: executing "fusionauth/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}
```

### My hosts and TLS Values:
```
ingress:
  # ingress.enabled -- Enables ingress creation for fusionauth.
  enabled: true
  # ingress.annotations -- Configure annotations to add to the ingress object
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/tls-acme: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
  paths:
    - /
  extraPaths: []
  # ingress.hosts -- List of hostnames to configure the ingress with
  hosts:
    - auth.mydomain.tld
  tls:
    - secretName: fusionauth-app
      hosts:
        - auth.mydomain.tld
```

The same values works (with some warning about the networking api) in the Helm Chart with application version `1.21.0` and commit `35cf5dc`

**Comment by drpebcak** [comment]
Take a look at my MR and see if those changes resolve this.

**Comment by soroushtaheri** [comment]
Thanks. #74 solved the issue.

**Comment by miaucl** [comment]
@drpebcak The current format proposed by the `helm create ...` is 
```
# Default values for template-v1.22.1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
``` 

where the definition of the ingress-hosts are "pre-fix" (https://github.com/FusionAuth/charts/pull/74/files) and now do not confirm anymore. Is there a specific reason why this format has been chosen instead?



Here is the template form the most recent `helm` version.
[template-v1.22.1.zip](https://github.com/FusionAuth/charts/files/7235193/template-v1.22.1.zip)
