### ISSUE TITLE
Set root API key via secret

### ISSUE THREAD

**Issue by nodesocket** [FusionAuth/charts#76]
**Is your feature request related to a problem? Please describe.**

I'd like to use a Kubernetes secret to store the default root API key used with Kickstart. Is this possible?

Currently  I have to hard-code it in the `values.yaml` and I can't use Helm variables or functions:

```
kickstart:
    enabled: true
    data:
      kickstart.json: |
        {
          "variables": {
          },
          "apiKeys": [{
            "key": "api-key-here",
            "description": "Root API Key"
          }]
        }
```

**Comment by nodesocket** [comment]
Is there anyway to work around this? I'd like to pass the root api key from a parent chart into the FusionAuth chart.

**Comment by bguyza** [comment]
I'm looking into this. I do not believe there is currently a way to pass a secret to a kickstart configuration. You could modify ConfigMap, but I don't believe references to secrets are available in ConfigMaps.  Let me confirm that and see if I can come up with some potential solutions.

**Comment by robotdan** [comment]
Can you use an environment variable? 

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables
https://fusionauth.io/docs/v1/tech/installation-guide/kickstart/#using-environment-variables

**Comment by bguyza** [comment]
*Update*: 

1.  Reference the secret on the container.  Something like this: 
```
env:
  - name: API_KEY
     valueFrom:
        secretKeyRef:
            name: api-key
            key: API_KEY
```
2.  When FusionAuth is deployed, you should now have access to that value as an environment variable on the pod. (https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables)
3. Modify `kickstart.json` in `values.yaml` to point to this environment variable:
```
...
          "apiKeys": [
            {
              "key": "#{ENV.API_KEY}",
              "description": "Core API Key"
            }
          ],
...
```

@nodesocket let me know if I'm missing anything for your use-case?  I'd be happy to consider adding this type of configuration option to our helm charts.

Thanks.

**Comment by nodesocket** [comment]
@bguyza thanks for the reply and assistance with this.

In step `1` you say:

```
env:
  - name: API_KEY
     valueFrom:
        secretKeyRef:
            name: api-key
            key: API_KEY
```

However, I am looking to pass the default root API Key from a parent chart. I.E. the fusionauth chart is a child chart. Therefore, I don't see a way to set a fusionauth environment variable upstream. However, I can create a secret. I am already doing this with `fusionauth-creds` and setting the passwords. It would be extremely helpful, if I can also set the root api key via this secret as well.


My existing secret definition `fusionauth-creds`:

```
{{- $global := .Values.global | default dict }}
{{- $postgresql := $global.postgresql | default dict }}
apiVersion: v1
data:
  rootpassword: {{ $postgresql.password | default .Values.fusionauth.database.root.password | b64enc | quote }}
  password: {{ .Values.fusionauth.database.password | b64enc | quote }}
kind: Secret
metadata:
  name: fusionauth-creds
type: Opaque
```

Perhaps we can just add:

```
data:
  rootAPIkey: super-secure-value-here
```
