### ISSUE TITLE
Helm chart points to a broken point release

### ISSUE THREAD

**Issue by smcoll** [FusionAuth/charts#9]
Helm chart is still referencing 1.15.6, which has a SAML regression fixed in 1.15.7.

**Comment by nodesocket** [comment]
Bumping the `image:tag` worked:

```
  image:
    repository: fusionauth/fusionauth-app
    tag: 1.15.7
    pullPolicy: IfNotPresent
```
